function createType(type, payload) {
	return {
		type,
		payload
	};
}

const auth = {
	GET_AUTH: 'GET_AUTH',
	GET_AUTH_SUCCESS: 'GET_AUTH_SUCCESS',
	GET_AUTH_ERROR: 'GET_AUTH_ERROR',

	SET_AUTH: 'SET_AUTH',
	SET_AUTH_SUCCESS: 'SET_AUTH_SUCCESS',
	SET_AUTH_ERROR: 'SET_AUTH_ERROR',

	SUBMIT_AUTH: 'SUBMIT_AUTH',
};

const post = {
	GET_ALL_POSTS: 'GET_ALL_POSTS',
	GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
	GET_ALL_POSTS_ERROR: 'GET_ALL_POSTS_ERROR',

	GET_POST_DETAILS: 'GET_POST_DETAILS',
	GET_POST_DETAILS_SUCCESS: 'GET_POST_DETAILS_SUCCESS',
	GET_POST_DETAILS_ERROR: 'GET_POST_DETAILS',

	ADD_POST: 'ADD_POST',
	ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
	ADD_POST_ERROR: 'ADD_POST_ERROR'

};

const comment = {
	ADD_COMMENT: 'ADD_COMMENT',
	ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
	ADD_COMMENT_ERROR: 'ADD_COMMENT_ERROR'
};

export { createType };

// Export action types here
export { auth, post, comment };
